### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by Rocio01** [Rocio01/space-travelers#19]
Greetings

https://github.com/Rocio01/space-travelers/projects/1

We are two people on the project.

Kind regards

**Comment by BrianSammit** [comment]
# CHANGES REQUIRED 🔴 🛑
Hello @Rocio01 nad @Amalcxc, great job you are doing so far in this project. 💯
TO HIGHLIGHT:

- Great job distributing the task 
- Well done assigning the tasks

However, there are a few changes to make to move to the next project 🛠️ . Keep working hard 💪 💻 

## Required Changes ♻️

- [ ] Kindly fix the link that you provide. Your link must point to the[ GitHub project](https://github.com/Rocio01/space-travelers/projects/1). Currently, the link is pointing to [GitHub code](https://github.com/Rocio01/space-travelers).

Please make these required changes and send it again for another review 👍 💪
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
# HAPPY CODING!!! 😄 

![cat](https://user-images.githubusercontent.com/64173189/131593916-14c184cb-b5af-40f7-8fba-779155f154cb.gif)


**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

--------

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by BrianSammit** [comment]
# STATUS: APROVED :green_circle: :clap: 

Hello again 👋, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![Well-Done-Applause](https://user-images.githubusercontent.com/64173189/140821697-d3e63bea-0413-4118-86dd-a784bb2f9b22.gif)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
